advancedentalexport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from blog.views import blog_detail as bd
from blog.views import product_detail as pd
from home import views as myapp_views
from django.conf.urls import handler404, handler500

# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'MIT Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'My One Blog Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('sending-data/', include('enquiry.urls')),
    path('ultimate-smile-design/', include('usd.urls')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
    path('<str:pk>/', bd, name='blogd'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# handler404 = myapp_views.error_404
# handler500 = myapp_views.error_500

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('', views.blog_home, name='blog'),
    path('search-in-blogs', views.myblogsearch, name='myblogsearch'),
    path('all-blogs/', views.blog_list, name='blog_list'),
    path('all-blogs/<str:pk>/', views.cat_list, name='cat_list'),
] 

home/urls.py
from django.urls import path
from . import views
from blog.views import blog_detail as bd

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('verify-warranty/', views.verify_warrenty, name='verify_warrenty'),
    path('contact/', views.contact, name='contact'),
    path('contact-us/', views.contact_new, name='contact_new'),
    path('submit-stl-file/', views.stl, name='stl'),
    path('before-after/', views.beforeafter, name='beforeafter'),
    path('exhibition-gallery/', views.exhibition, name='exhibition'),
    path('career/', views.career, name='career'),
    path('event-gallery/<str:pk>/', views.eventgallery, name='eventgallery'),
    path('categories/', views.categories, name='categories'),
    path('categories/<str:pk>/', views.categoriesd, name='categoriesd'),
    path('blogs/', views.blogs, name='blogs'),
    path('search/', views.search, name='search'),
    path('gallery/', views.gallery, name='gallery'),
    path('terms-and-condition/', views.privacy, name='privacy'),
    path('cookie-policy/', views.cookie, name='cookie'),
    path('about-us/', views.about, name='about'),
    path('checkup/', views.checkup, name='checkup'),
    path('guest-posting/', views.gp, name='gp'),
    path('faq', views.faq, name='faq'),
    path('sitemap.xml/', views.sitemap, name='sitemap'),
    path('robots.txt/', views.robots, name='robot'),
    path('upload/', views.file_upload, name='upload'),
    path('testimonals/', views.testimonals, name='testimonals'),
    path('login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('web-story/', views.web_story, name='web_story'),
    path('web-story/<slug:story_slug>/', views.web_story_detail, name='web_story_detail'),
    # path('services/', views.service_view, name='service_view'),
    path('client-profile/<str:pk>/<str:fk>/', views.ext_api, name='ext_api'),
    path('print-order/', views.print_order, name='print_order'),
    path('print-payment/', views.print_payment, name='print_payment'),
    path('print-statments/<str:pk>/<str:did>/', views.print_statment, name='print_statment'),
    path('print-invoice/<str:pk>/<str:did>/', views.print_invoice, name='print_invoice'),
    path('api-login/', views.api_user_login, name='api_user_login'),
    path('api-logout/<str:pk>/<str:did>/', views.api_logout, name='api_logout'),
    # path('Events/', views.ade_events, name='Events'),
    # path('best-dental-lab/', views.bdl, name='bdl'),
    path('best-dental-lab-in-<str:pk>/', views.bdld, name='bdld'),
    path('blog/<str:pk>/', bd, name='blogd'),
    path('quicks-links/', views.connect, name='connect'),
]

usd/urls.py
from django.urls import path
from . import views
app_name='usd'
urlpatterns = [
    path('', views.usd, name='usd'),
    
] 

blog/views.py
from django.shortcuts import render, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def blog_home(request):
    data1 = Blog.objects.all().order_by('-id')
    page = request.GET.get('page', 1)
    data2 =  Category.objects.all().order_by('-id')
    data3 = Blog.objects.filter(main3=True).order_by('-id')
    paginator = Paginator(data1, 9)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)


    context = {
        'data':data,
        'data2':data2,
        'data3':data3,
    }
    return render(request, 'blog_home.html', context)

# Create your views here.
def product_detail(request, pk):
    data = Product.objects.get(slug=pk)
    data2 =  SubProduct.objects.filter(product=data).order_by('-id')
    data3 = Blog.objects.filter(main3=True).order_by('-id')
    data4 = Faqpage.objects.filter(product=data).order_by('-id')
    
    context = {
        'data':data,
        'data2':data2,
        'data3':data3,
        'data4':data4,
    }
    return render(request, 'product_detail.html', context)


def blog_detail(request, pk):
    try:
        data = Blog.objects.get(slug=pk)
        blog_id = data.id
        data1 = Blog.objects.all().order_by('id')[:2]
        data2 =  Category.objects.all().order_by('-id')
        data3 = Blog.objects.filter(main3=True).order_by('-id')
        context = {
        'data':data,
        'data1':data1,
        'data2':data2,
        'data3':data3,
        }
        return render(request, 'blog_detail.html', context)

    except:
        data = Product.objects.get(slug=pk)
        data2 =  Category.objects.all().order_by('-id')
        data3 = Blog.objects.filter(main3=True).order_by('-id')
        data4 = Faqpage.objects.filter(product=data).order_by('-id')
        
        context = {
            'data':data,
            'data2':data2,
            'data3':data3,
            'data4':data4,
        }
        return render(request, 'product_detail.html', context)


    


def myblogsearch(request):
    print('here')
    if request.method=="GET":
        q = request.GET.get('q')
    else:
        q= "a"    
    print(q)
    data1 = Blog.objects.filter(content__contains=q).order_by('-id')
    if data1:
        page = request.GET.get('page', 1)
        paginator = Paginator(data1, 10)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)

    else:
        data1 = Blog.objects.filter(content__contains="a").order_by('-id')
        page = request.GET.get('page', 1)
        paginator = Paginator(data1, 10)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
    data2 =  Category.objects.all().order_by('-id')
    data3 = Blog.objects.filter(main3=True).order_by('-id')
    context = {
        'data':data,
        'data2':data2,
        'data3':data3,
    }
    return render(request, 'blog_home.html', context)




def blog_list(request):
    data1 = Blog.objects.all().order_by('-id')
    page = request.GET.get('page', 1)

    
    paginator = Paginator(data1, 10)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    response = render(request, 'blog_list.html', {'data' : data})
    try:
        page_num = int(page)
        if 2 <= page_num <= 10 :
            response['X-Robots-Tag'] = 'noindex, nofollow'
    except (ValueError, TypeError) :
        pass
    return response    

def cat_list(request, pk):
    
    data1 = Blog.objects.filter(category__id=pk).order_by('-id')
    page = request.GET.get('page', 1)

    
    paginator = Paginator(data1, 10)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)


    context = {
        'data':data,
    }
    return render(request, 'blog_list.html', context)

blog/templates/aside.html
{% load static %}
<!-- SIDEBAR -->
    <aside id="sidebar" class="col-lg-4">


        <!-- SEARCH FIELD --> 
        <div id="search-field" class="sidebar-div mb-50">								
            <form class="input-group mb-3" action="{% url 'blog:myblogsearch' %}" method="GET">
                {% csrf_token %}
                {% comment %} update this line {% endcomment %}
                  <input type="text" class="form-control" name="q" placeholder="Search" aria-label="Search" aria-describedby="search-field" value="{{ request.GET.q }}" >
                 <div class="input-group-append">
                    <button class="btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                 </div>
            </form>
        </div>
        <!-- TEXT WIDGET -->						
        <div id="txt-widget" class="sidebar-div mb-50">          
            <!-- Title -->
            <h5 class="h5-sm steelblue-color">Advance Dental Export</h5>

            {% for i in data.review  %}
                <!-- Head of Clinic -->
                <div class="txt-widget-unit mb-15 clearfix d-flex align-items-center">
                
                    <!-- Avatar -->
                    <div class="txt-widget-avatar">
                        <img src="{{i.image.url}}" alt="testimonial-avatar" style="border-radius: 50px;">
                    </div>

                    <!-- Data -->
                    <div class="txt-widget-data">
                        <h5 class="h5-md steelblue-color">{{i.name}}</h5>	
                        <span>5 Star Rating In Google</span>	
                    </div>

                </div>	<!-- End Head of Clinic -->	
                
                <!-- Text -->
                <p class="p-sm">{{i.review}}
                </p>
                <span class="mt-3">
                    <!-- Title -->
            <hr>
            
            {% endfor %}
                                                          
        </div>	<!-- END TEXT WIDGET -->


        <!-- BLOG CATEGORIES --> 
        <div class="blog-categories sidebar-div mb-50">
                
            <!-- Title -->
            <h5 class="h5-sm steelblue-color">Categories</h5>

            <ul class="blog-category-list clearfix">
                
                {% for ie in data2 %}
                <li><a href="#"><i class="fas fa-angle-double-right blue-color"></i> {{ie.category}}</a> <span>({{ie.tot}})</span></li>
            
                {% endfor %}
                    
            </ul>

        </div>


        <!-- POPULAR POSTS -->
        <div class="popular-posts sidebar-div mb-50">
                
            <!-- Title -->
            <h5 class="h5-sm steelblue-color">Popular Posts</h5>

            <ul class="popular-posts">
                
                {% for ie in data3 %}
                    
                <!-- Popular post #1 -->
                <li class="clearfix d-flex align-items-center">

                    <!-- Image -->
                    <img class="img-fluid" src="{{ie.image.url}}" style="height: 60px;" alt="blog-post-preview" />

                    <!-- Text -->
                    <div class="post-summary">
                        <a href="{% url 'blogd' ie.slug %}">{{ie.h1}} ...</a>
                    </div>

                </li>
             
                {% endfor %}
                    
            </ul>

        </div>
        <!-- TAGS CLOUD -->
        <div class="tags-cloud sidebar-div mb-50">
                
            <!-- Title -->
            <h5 class="h5-sm steelblue-color">Products</h5> 
          {% for ie in product %}
          <span class="badge"><a href="{% url 'blogd' ie.slug %}">{{ie.h1}}</a></span>
          {% endfor %}
            
     						
        </div>

        <!-- IMAGE WIDGET -->						
        <div class="image-widget sidebar-div d-flex mx-auto justify-content-center">
            <a href="#">
                <img class="img-fluid" src="{% static 'harsh.jpg' %}" alt="image-widget" />
            </a>																		
        </div>

        <!-- SIDEBAR TIMETABLE -->
        <div class="sidebar-timetable sidebar-div mb-50">

            <!-- Title -->
            <h5 class="h5-md mb-20 steelblue-color">Haresh Savani, Founder
            </h5>

            <!-- Text -->
            <p class="p-sm">As an accomplished founder and CEO, seasoned digital dental technician, experienced ceramist, and a guide to thousands of budding professionals, my vision is to bring a dental renaissance to the global canvas.
            </p>

            <!-- Button -->
            <a href="{% url 'home:contact' %}" class="btn btn-blue blue-hover mt-10">Get In Touch</a>

        </div>	<!-- END SIDEBAR TIMETABLE -->


        

    </aside>	<!-- END SIDEBAR -->

blog/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}
<title>{% spaceless %}{{data.title}}{% endspaceless %}</title>
<meta name="description" content="{% spaceless %}{{data.description}}{% endspaceless %}">
<meta name="keyword" content="{% spaceless %}{{data.keyword}}{% endspaceless %}">
<link rel="canonical" href="{% spaceless %}{{data.canonical}}{% endspaceless %}">
<!-- Opengraphs -->
<meta property="og:title" content="{% spaceless %}{{data.title}}{% endspaceless %}" />
<meta property="og:type" content="{% spaceless %}{{data.og_type}}{% endspaceless %}" />
<meta property="og:url" content="{% spaceless %}{{data.canonical}}{% endspaceless %}" />
<meta property="og:image" content="{% spaceless %}{{data.image.url}}{% endspaceless %}" />
<meta property="og:description" content="{% spaceless %}{{data.description}}{% endspaceless %}" />

<meta name="twitter:card" content="{% spaceless %}{{data.description}}{% endspaceless %}" />
<meta name="twitter:site" content="@thegrandindianroute" />
<meta name="twitter:title" content="{% spaceless %}{{data.title}}{% endspaceless %} " />
<meta name="twitter:description" content="{% spaceless %}{{data.description}}{% endspaceless %}" />
<meta name="twitter:image" content="{% spaceless %}{{data.image.url}}{% endspaceless %}" />    
{% endblock seo %}

{% block css %}
<style>
    p{
        font-size: 18px;
    }
    .content p{
        width: 100%!important;
    }
    .content ul,.content  ol{
        padding-left: 25px!important;
    }
</style>
{% endblock css %}
    


{% block body %}


<!-- BREADCRUMB
			============================================= -->
			<div id="breadcrumb" class="division">
				<div class="container">
					<div class="row">						
						<div class="col">
							<div class=" breadcrumb-holder">

								<!-- Breadcrumb Nav -->
								<nav aria-label="breadcrumb">
								  	<ol class="breadcrumb">
								    	<li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
								    	<li class="breadcrumb-item active"><a href="{% url 'blog:blog' %}">Blogs</a></li>
								    	
								  	</ol>
								</nav>

								<!-- Title -->
                                <h1 class="h4-sm steelblue-color">{{data.h1}}</h1>
								{% comment %} <h4 class="h4-sm steelblue-color">{{data.h1}}</h4> {% endcomment %}
							</div>
						</div>
					</div>  <!-- End row -->	
				</div>	<!-- End container -->		
			</div>	<!-- END BREADCRUMB -->	




			<!-- BLOG PAGE CONTENT
			============================================= -->
			<div id="blog-page" class="wide-100 blog-page-section division">
				<div class="container">
				 	<div class="row">


				 		<!-- BLOG POSTS HOLDER -->
				 		<div class="col-lg-12">
				 			<div class="posts-holder pr-30">

                                <div class="single-blog-post pr-30">

				 			
                                    <!-- BLOG POST IMAGE -->
                                    <div class="blog-post-img mb-40">
                                       <img class="img-fluid" src="{{data.image.url}}" alt="{{data.h1}}">		
                                    </div>	
    
   
                                   <!-- BLOG POST TEXT -->
                                   <div class="sblog-post-txt">
                                    <h2 class="h1-sm steelblue-color">{{data.h1}}</h2>
                                    <h2 style="font-size: 1.1rem !important; font-weight: 100 !important; color: rgba(0,0,0,0.6);">Posted {{data.published}} by <span>{{data.author}}</span></h2>
                                    
                                        <div class="content mt-4">
                                            
                                        {{data.content|safe}}
                                      
                                        </div>
                                       <!-- BLOG POST SHARE LINKS -->
                                       <div class="post-share-links">
   
                                           <!-- POST TAGS -->
                                           <div class="post-tags-list">
                                              
                                              {% for ie in data.tag.all %}
                                              <span><a href="#">{{ie}}</a></span>	
                                              
                                              {% endfor %}
                                                									
                                           </div>
   
                                           <!-- POST SHARE ICONS -->
                                           <div class="post-share-list">
                                               <ul class="share-social-icons clearfix">	
                                                   <li><a href="#" class="share-ico ico-facebook"><i class="fab fa-facebook-f"></i> Share</a></li>
                                                   <li><a href="#" class="share-ico ico-twitter"><i class="fab fa-twitter"></i> Tweet</a></li>	
                                                   <li><a href="#" class="share-ico ico-google-plus"><i class="fab fa-pinterest-p"></i> Pin It</a></li>					
                                                   <li><a href="#" class="share-ico ico-google-plus"><i class="fab fa-instagram"></i> Share</a></li>
                                               </ul>
                                           </div>
   
                                       </div>	<!-- END BLOG POST SHARE -->

   
                                   </div>	<!-- END BLOG POST TEXT -->
   
   
                                   <!-- ABOUT POST AUTHOR -->
                                   <div class="author-senoff">
                                       
                                       <!-- Avatar -->	
                                       <img src="{{data.author.image.url}}" alt="{{data.author}}">
   
                                       <!-- Text -->
                                       <div class="author-senoff-txt">
   
                                           <!-- Title -->
                                           <h5 class="h5-sm steelblue-color">Published by {{data.author}}</h5>
                                           <p>{{data.author.description|safe}}
                                           </p>
   
                                       </div>
   
                                   </div>	<!-- END ABOUT POST AUTHOR -->
   
   
                                   <!-- RELATED POSTS -->
                                   <div class="related-posts">
   
                                       <!-- Title -->	
                                       <h5 class="h5-md steelblue-color">Related Posts</h5>	
   
   
                                       <div class="row">
                                            {% for ie in data1 %}
                                             <!-- BLOG POST #1 -->
                                             <div class="col-md-6">
                                              <!-- BLOG POST #1 --> 
                                                    <div class="blog-post">
                                            
                                                        <!-- BLOG POST IMAGE -->
                                                        <div class="blog-post-img">
                                                        <img class="img-fluid" src="{{ie.image.url}}" alt="{{ie.h1}}" />	
                                                    </div>

                                                        <!-- BLOG POST TITLE -->
                                                    <div class="blog-post-txt">

                                                        <!-- Post Title -->
                                                        <h5 class="h5-xl steelblue-color">
                                                            <a href="{% url 'blogd' ie.slug %}">{{ie.h1}}</a></h5>

                                                        <!-- Post Data -->
                                                        <span>{{ie.published}} by <span>{{ie.author}}</span></span>

                                                        <!-- Post Text -->
                                                        <p>{{ie.description}} ...
                                                        </p>

                                                    </div>

                                                </div>	
                                            </div>	<!-- END  BLOG POST #1 -->
                                          {% endfor %}
                                            
   
   
                                     
   
                                       </div>	<!-- End row -->
   
                                   </div>	<!-- END RELATED POSTS -->
   
                                   <hr>
                                  
   
   
                                   <!-- COMMENT FORM -->
                                   {% comment %} <div id="leave-comment">
                                       
                                       <!-- Title -->
                                       <h5 class="h5-md steelblue-color">Leave a Comment</h5>
                                       
                                       <!-- Text -->
                                       <p class="grey-color">Your email address will not be published. Required fields are marked *</p>
   
                                       <form name="commentForm" class="row comment-form" novalidate="novalidate">
   
                                           <div id="input-message" class="col-md-12 input-message">
                                               <p>Add Comment *</p>
                                               <textarea class="form-control message" name="message" rows="6" placeholder="Enter Your Comment Here* ..." required=""></textarea>
                                           </div> 
                                                               
                                           <div id="input-name" class="col-md-12">
                                               <p>Name*</p>
                                               <input type="text" name="name" class="form-control name" placeholder="Enter Your Name*" required=""> 
                                           </div>
                                                   
                                           <div id="input-email" class="col-md-12">
                                               <p>Email*</p>
                                               <input type="text" name="email" class="form-control email" placeholder="Enter Your Email*" required=""> 
                                           </div>
                                                            
                                           <!-- Contact Form Button -->
                                           <div class="col-lg-12 mt-15 form-btn"> 						                 
                                               <button type="submit" class="btn btn-blue blue-hover submit">Post Comment</button> 
                                           </div>
                                                                                         
                                           <!-- Contact Form Message -->
                                           <div class="col-md-12 comment-form-msg text-center">
                                               <div class="sending-msg"><span class="loading"></span></div>
                                           </div>  
                                                                     
                                       </form>									
                                   
                                   </div>	<!-- END COMMENT FORM --> {% endcomment %}
   
   
                                </div>

				 			</div>
				 		</div>	 <!-- END BLOG POSTS HOLDER -->



						{% comment %} {% include 'aside.html' %} {% endcomment %}
				 		
				 	</div>	<!-- End row -->	
				 </div>	 <!-- End container -->
			</div>	<!-- END BLOG PAGE CONTENT -->




{% endblock body %}
    
{% block js %}

{{data.schema|safe}}

{% endblock js %}
    

blog/templates/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% block seo %}
<title>All Blogs - The Advance Dental Export</title>
<meta property="og:locale" content="en_US">
<meta property="og:type" content="article">
<meta property="og:title" content="All Blogs - Stay Informed with Advance Dental Export Blogs">
<meta property="og:description" content="The best collection of all the blogs delivering valueable insights on Digital Dentistry.">
<meta property="og:url" content="Article">
<meta property="og:site_name" content="All Blogs - The Advance Dental Export">
<meta property="article:publisher" content="">
<meta property="article:section" content="Blog">
<meta property="og:image" content="{% static 'seo/blog/b125/8.jpg' %}">
<meta property="og:image:secure_url" content="{% static 'seo/blog/b125/8.jpg' %}">
<meta property="og:image:width" content="327">
<meta property="og:image:height" content="218">
<meta property="og:image:alt" content="All Blogs - The Advance Dental Export">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:description" content="The best collection of blogs delivering valueable insights on Digital Dentistry.">
<meta name="twitter:title" content="All Blogs - The Advance Dental Export">
<meta name="twitter:image" content="{% static 'seo/blog/b125/8.jpg' %}">
<style>
   .row{
       padding: 0!important;margin:0!important ;
   }
</style>
{% endblock seo %} 
{% block css %}
{% endblock css %}
    


{% block body %}
<section class="breadcrumb-outer text-center">
	<div class="container">
		<div class="breadcrumb-content">
			<h2 class="white">All  Blogs</h2>
			<nav aria-label="breadcrumb">
				<ul class="breadcrumb">
					<li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
					<li class="breadcrumb-item active" aria-current="page">Blogs</li>
				</ul>
			</nav>
		</div>
	</div>
	<div class="overlay"></div>
</section>
<section class="blog blog-fullwidth">
	<div class="container">
		<div class="row">
			
            {% for ie in data %}
            <div class="col-lg-4 col-12 mar-bottom-30 mansonry-item">
				<div class="grid">
					<div class="grid-item">
						<div class="grid-image"><img src="{{ie.image.url}}" alt="{{ie.h1}}">
							<div class="overlay"></div>
						</div>
						<div class="gridblog-content">
							<h3><a href="{% url 'blog_detail' ie.slug %}">{{ie.h1}}</a></h3>
							<p>
                                {{ie.description}}
                            </p><a href="{% url 'blog_detail' ie.slug %}" class="biz-btn biz-btn1">Read More</a></div>
					</div>
				</div>
			</div>
            {% endfor %}
          
		</div>
		
	</div>
</section>

<div class="col-md-12">
    <div class="blog-button text-center col-md-12">
        {% if data.has_other_pages %}
        <div class="pagination-content text-center">
            <ul class="pagination">
                {% if data.has_previous %}
                <li > <a href="?page={{ data.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                {% else %}
                <li ><a href="javascript:void(0)"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                {% endif %}
                
                {% for i in data.paginator.page_range %}
                    {% if data.number == i %}
                    <li class="active"> <a href="javascript:void(0);" class="bg-primary">{{i}} </a>
                    </li>
                    {% elif i > data.number|add:'-7' and i < data.number|add:'7' %}
                    <li><a href="?page={{ i }}"> {{i}} </a></li>
                    {% endif %}
                {% endfor %}
                {% if data.has_next %}
                <li><a href="?page={{ data.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                {% else %}
                <li><a href="javascript:void(0)"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}

    </div>
</div>


{% endblock body %}
    


{% block javascript %}
{% endblock javascript %}
    