advancedentalexport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from blog.views import blog_detail as bd
from blog.views import product_detail as pd
from home import views as myapp_views
from django.conf.urls import handler404, handler500

# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'MIT Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'My One Blog Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('sending-data/', include('enquiry.urls')),
    path('ultimate-smile-design/', include('usd.urls')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
    path('<str:pk>/', bd, name='blogd'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# handler404 = myapp_views.error_404
# handler500 = myapp_views.error_500

enquiry/urls.py
from django.urls import path
from . import views
app_name='enquiry'
urlpatterns = [
    path('newsletter/', views.newsletter, name='newsletter'),
    path('review/', views.review, name='review'),
    path('contact-data/', views.contactd, name='contactd'),
    
] 

home/urls.py
from django.urls import path
from . import views
from blog.views import blog_detail as bd

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('verify-warranty/', views.verify_warrenty, name='verify_warrenty'),
    path('contact/', views.contact, name='contact'),
    path('contact-us/', views.contact_new, name='contact_new'),
    path('submit-stl-file/', views.stl, name='stl'),
    path('before-after/', views.beforeafter, name='beforeafter'),
    path('exhibition-gallery/', views.exhibition, name='exhibition'),
    path('career/', views.career, name='career'),
    path('event-gallery/<str:pk>/', views.eventgallery, name='eventgallery'),
    path('categories/', views.categories, name='categories'),
    path('categories/<str:pk>/', views.categoriesd, name='categoriesd'),
    path('blogs/', views.blogs, name='blogs'),
    path('search/', views.search, name='search'),
    path('gallery/', views.gallery, name='gallery'),
    path('terms-and-condition/', views.privacy, name='privacy'),
    path('cookie-policy/', views.cookie, name='cookie'),
    path('about-us/', views.about, name='about'),
    path('checkup/', views.checkup, name='checkup'),
    path('guest-posting/', views.gp, name='gp'),
    path('faq', views.faq, name='faq'),
    path('sitemap.xml/', views.sitemap, name='sitemap'),
    path('robots.txt/', views.robots, name='robot'),
    path('upload/', views.file_upload, name='upload'),
    path('testimonals/', views.testimonals, name='testimonals'),
    path('login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('web-story/', views.web_story, name='web_story'),
    path('web-story/<slug:story_slug>/', views.web_story_detail, name='web_story_detail'),
    # path('services/', views.service_view, name='service_view'),
    path('client-profile/<str:pk>/<str:fk>/', views.ext_api, name='ext_api'),
    path('print-order/', views.print_order, name='print_order'),
    path('print-payment/', views.print_payment, name='print_payment'),
    path('print-statments/<str:pk>/<str:did>/', views.print_statment, name='print_statment'),
    path('print-invoice/<str:pk>/<str:did>/', views.print_invoice, name='print_invoice'),
    path('api-login/', views.api_user_login, name='api_user_login'),
    path('api-logout/<str:pk>/<str:did>/', views.api_logout, name='api_logout'),
    # path('Events/', views.ade_events, name='Events'),
    # path('best-dental-lab/', views.bdl, name='bdl'),
    path('best-dental-lab-in-<str:pk>/', views.bdld, name='bdld'),
    path('blog/<str:pk>/', bd, name='blogd'),
    path('quicks-links/', views.connect, name='connect'),
]

usd/urls.py
from django.urls import path
from . import views
app_name='usd'
urlpatterns = [
    path('', views.usd, name='usd'),
    
] 

home/models.py
from django.db import models

# Create your models here.

home/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.http import JsonResponse, FileResponse, Http404
from blog.models import *
from enquiry.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from enquiry.forms import STLForm, STLFileForm, LoginForm
from django.contrib import messages
from django.views.decorators.csrf import ensure_csrf_cookie
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string, get_template
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
import requests

# from enquiry.models import InstaPost
# Create your views here.
def home(request):
    # data = InstaPost.objects.all().order_by('-id')
    main3 = Blog.objects.filter(main3=True).order_by('-id')[:3]
    data = Testimonials.objects.all().order_by('-id')[:20]
    data2 = Blog.objects.all().order_by('-id')[:3]
    client = Client.objects.all().order_by('-id')
    gallery = Gallery.objects.all().order_by('-id')[:7]
    gallery21 = BeforeAfter.objects.all().order_by('-id')[:7]
    video      =VideoTestimonals.objects.all().order_by('-id')[:4]
    context = {
        # 'data':data,
        'main3':main3,
        'data':data,
        'data2':data2,
        'client':client,
        'gallery':gallery,
        'gallery21':gallery21,
        'video':video,
        
    }
    return render(request, 'index.html', context)

def testimonals(request):
    videoData = VideoTestimonals.objects.all()
    data = Testimonials.objects.all().order_by('-id')[:20]
    context = { 
        'videoData':videoData,
         'data':data,
    }
    return render(request, 'testimonals.html', context)


def verify_warrenty(request):
    
    # Input parameters
    
    
    if request.method == 'POST':
        orderId = request.POST.get('id') 
        authenticationId = request.POST.get('auth') 
        # Set your parameters
        api_url = "https://adesurat.com/API.php?call=get_warranty_details"
        orderId = str(orderId)
        authenticationId = str(authenticationId)
        
        # Data to be sent in form-encoded format
        data = {
            "authenticationId": authenticationId,
            "orderId": orderId
        }
        
        # Make the POST request with data as form-encoded
        response = requests.post(api_url, data=data)
        # Check if request was successful (status code 200)
        if response.status_code == 200:
            # Parse JSON response
            data = response.json()
            # Extract data from the "data" object
            warranty_data = data.get("data", {})
            status = data.get("status", False)
            # Pass data to template
            
            return render(request, 'verify_warrenty_r.html', {'status': status, 'warranty_data': warranty_data})
        else:
            # If request fails, handle it appropriately
            messages.error(request, 'Your Warrenty Card Is Invalid')
            return redirect('home:verify_warrenty')
        
    return render(request, 'verify_warrenty.html')


def blogd(request, pk):
    data =  Blog.objects.get(slug=pk)
    data2 =  Blog.objects.all().order_by('-id')[:2]
    for ie in data.category.all():
        cat = ie.category
        print(cat)
    data3 =  Category.objects.get(category=cat)
    context = {
        'data':data,
        'data2':data2,
        'data3':data3,
    
    }
    return render(request, 'blogd.html', context)

def contact(request):
    data= ContactDetails.objects.all()
    context = {
        'data':data,
    }
    return render(request, 'contact.html', context)
    

def contact_new(request):
    data= ContactDetails.objects.all()
    context = {
        'data':data,
    }
    return render(request, 'contact_new.html', context)

        
def connect(request):
    context = {
        'hide_social_image': True,
    }
    return render(request, 'connect.html', context)
    
def career(request):
    context = {

    }
    return render(request, 'career.html', context)


def exhibition(request):
    context = {
    }
    return render(request, 'exhibition.html', context)


def beforeafter(request):
    data = BeforeAfter.objects.all()
    context = {
        'data':data,
    }
    return render(request, 'beforeafter.html', context)

def stl(request):
            
    if request.method == 'POST':
        
        documents = request.FILES.getlist('files')
        
        nam = request.POST.get('name')
        phone = request.POST.get('contact')
        message = request.POST.get('message')
        name = STLFile.objects.create(name=nam, contact=phone, message=message)

        name.save()
        name = STLFile.objects.all().last()
        
        
        print(documents, '========================')
        
        for f in documents:
            pp = STLFileData.objects.create(stl_data=name, files=f)
            pp.save()

        html_content = render_to_string ('stlmail.html',{ 
            'name':nam, 'phone':phone, 'message':message
        })
        email_from = settings.EMAIL_HOST_USER
        subject = 'New Data In STL Form'
        message = "You have a new data in STL form."
        recipient_list = ['stl@advancedentalexport.com']
        # send_mail( subject, message, email_from, recipient_list, html_message=html_content, fail_silently=False )

        messages.success(request, 'Your STL File Is Uploaded Successfully')
        # return redirect('home:home')  
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))  




    d = STLFileForm()
    context = {
    'd':d
    }
    return render(request, 'stl.html', context)



def file_upload(request):
    if request.method == 'POST':
        my_file=request.FILES.getlist('files')
        print(my_file)
        for f in my_file:
            print('a')

        return HttpResponse('')
    return JsonResponse({'post':'fasle'})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('home:dashboard')
    else:
        if request.method == "POST":
            # your sign in logic goes here
            form = LoginForm(request.POST)
            if form.is_valid():
                username=form.cleaned_data['username']
                password=form.cleaned_data['password']
                #authenticate checks if credentials exists in db
                user = authenticate(username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('home:dashboard')

                    else:
                        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

                        
                else:
                    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

    context = {
    
    }
    return render(request, 'login.html', context)
    


@login_required(login_url = 'home:user_login')
def dashboard(request):
    if request.user.is_staff:
        data = STLFile.objects.all().order_by('-id')
        context = {
            'data':data,
        }
        return render(request, 'dashboard.html', context)
    else:
        return redirect('home:home')

def singUser(request):
    context = {

    }
    return render(request, 'singup.html', context)


def eventgallery(request, pk):
    
    data1 =  EventsGallery.objects.filter(category__slug=pk).order_by('-id')
    cat = Events.objects.get(slug=pk)
    page = request.GET.get('page', 1)
    paginator = Paginator(data1, 12)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    response = render(request, 'eventgallery.html', {'data': data, 'cat': cat})
    # Add noindex for specific pages (e.g., ?page=2 and onward)
    try:
        page_num = int(page)  # Convert page to integer
        if page_num >= 3:  # Apply noindex to pages 2 and beyond
            response['X-Robots-Tag'] = 'noindex, nofollow'
    except (ValueError, TypeError):
        pass  # Ignore if the page is not a valid number

    return response

def about(request):
    team = Team.objects.all()
    imagez = AboutImage.objects.all()
    context = {
        'team':team,
        'imagez':imagez,
    }
    return render(request, 'about.html', context)



def sitemap(request):
    return render(request, 'sitemap.xml', content_type='text/xml')

#end
def robots(request):
    return render(request, 'robot.txt', content_type='text')




def categories(request):
    data1 =  Category.objects.all().order_by('-id')
    page = request.GET.get('page', 1)

    
    paginator = Paginator(data1, 12)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {
        'data':data,
    }
    return render(request, 'categories.html', context)


def categoriesd(request, pk):
    data3 =  Category.objects.get(slug=pk)
    data1 =  Blog.objects.filter(category=data3).order_by('-id')
    data2 =  Blog.objects.filter(most_visited=True).order_by('-id')[:4]
    page = request.GET.get('page', 1)


    
    paginator = Paginator(data1, 12)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {
        'data':data,
        'data3':data3,
        'data2':data2,
    }
    return render(request, 'categories_blog.html', context)



def blogs(request):
    return redirect('blog:blog')

def gallery(request):

home/templates/all_blog.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}    
<title></title>
<meta name="description" content="" />
<link rel="canonical" href="https://www.myoneblog.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="" />
<meta property="og:description" content="" />
<meta property="og:url" content="https://www.myoneblog.com/" />
<meta property="og:site_name" content="My One Blog" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="" />
<meta name="twitter:title" content="" />

{% endblock seo %}

{% block css %}
{% endblock css %}
    


{% block body %}
<div class="breadcrumb-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb-inner">
					<div class="content">
						<h1 class="title">My One Blogs</h1>
						<ul class="page-list">
							<li class="list-item"><a href="{% url 'home:home' %}">Home</a></li>
							<li class="list-item"><a href="javascript:void(0);">Blogs</a></li>
							
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="blog-area-wrapper Political-blog-grid-wrapper" data-padding-top="100" data-padding-bottom="100">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="two-column">
					<div class="row">
						
                        {% for ie in data %}
                        <div class="col-md-6 col-lg-6">
							<div class="blog-grid-style-03 small-02">
								<div class="img-box"><img src="{{ie.image.url}}" alt="{{ie.title}}"></div>
								<div class="content">
									<div class="post-meta">
										<ul class="post-meta-list style-02">
											<li class="post-meta-item"><a href="author-profile.html"><span class="text author">{{ie.author}}</span></a></li>
											<li class="post-meta-item date"><span class="text">{{ie.published}}</span></li>
										</ul>
									</div>
									<h4 class="title"><a href="{% url 'home:blogd' ie.slug %}">{{ie.h1}}</a></h4></div>
                                    <p>{{ie.description}}... <a href="{% url 'home:blogd' ie.slug %}">read more</a></p>
							</div>
						</div>
						
                        {% endfor %}
                            

						 {% if data.has_other_pages %}
                            <div class="col-lg-12">
                                <div class="pagination" data-padding-top="50">
                                    
                                    <ul class="pagination-list">
                                        {% if data.has_previous %}
                                        <li><a href="?page={{ data.previous_page_number }}" class="page-number disable left-arrow"><i class="las la-angle-left"></i></a></li>
                                        {% else %}

                                        <li><a href="javascript:void(0);" class="page-number disable left-arrow"><i class="las la-angle-left"></i></a></li>
                                        {% endif %}
                                        {% for i in data.paginator.page_range %}
                                        {% if data.number == i %}
                                        <li><span class="page-number current">{{i}}</span></li>
                                        {% else %}  
                                    
                                        <li><a href="?page={{ i }}" class="page-number">{{i}}</a></li>
                                        {% endif %}
                                        {% endfor %}
                                        {% if data.has_next %}
                                        <li><a href="?page={{ data.next_page_number }}" class="page-number able right-arrow"><i class="las la-angle-right"></i></a></li>
                                        {% else %}

                                        <li><a href="javascript:void(0);" class="page-number able right-arrow"><i class="las la-angle-right"></i></a></li>
                                        {% endif %}
                                    </ul>


                                </div>
                            </div>
                        {% endif %}
					</div>
				</div>
			</div>
			<div class="col-sm-7 col-md-6 col-lg-4">
				<div class="widget-area-wrapper">
					{% include 'widget.html' %}
					<div class="widget">
						<div class="category style-01">
							<h4 class="widget-title style-01">Categories</h4>
							<ul class="widget-category-list">
                                
                                {% for ie in allcat %}
                                <li class="single-item"><a href="{% url 'home:categoriesd' ie.slug %}" class="wrap"><span class="left">{{ie.category}}</span>
                                     <span class="right">{{ie.tot}}</span></a></li>
							
                                {% endfor %}
                                    
                            </ul>
						</div>
					</div>
					<div class="widget">
						<div class="adds style-01">
							<a href="#"><img src="assets/img/ads-banner/half-page/03.jpg" alt=""></a>
						</div>
					</div>
					<div class="widget">
						<div class="recent-post style-01">
							<h4 class="widget-title style-01">Most Visted</h4>
							<ul class="news-headline-list style-01">
                                
                                {% for ie in data2 %}
                                <li class="news-heading-item">
									<h3 class="title"><a href="{% url 'home:blogd' ie.slug %}">
                                        {{ie.h1}}
                                    </a></h3>
									<div class="post-meta">
										<ul class="post-meta-list style-02">
											<li class="post-meta-item"><a href=""><span class="text author">{{ie.author}}</span></a></li>
											<li class="post-meta-item date"><span class="text">{{ie.published}}</span></li>
										</ul>
									</div>
								</li>
						        {% endfor %}
                                    
                                
							</ul>
						</div>
					</div>
					<div class="widget">
						<div class="tag style-01 black-bg">
							<h4 class="widget-title style-01">tags</h4>
							<ul class="tag-list">
								<li class="single-tag-item"><a href="#">News</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock body %}
    


{% block javascript %}
		
{% endblock javascript %}
    

home/templates/categories.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}    
<title></title>
<meta name="description" content="" />
<link rel="canonical" href="https://www.myoneblog.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="" />
<meta property="og:description" content="" />
<meta property="og:url" content="https://www.myoneblog.com/" />
<meta property="og:site_name" content="My One Blog" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="" />
<meta name="twitter:title" content="" />

{% endblock seo %}

{% block css %}
{% endblock css %}
    


{% block body %}
<div class="breadcrumb-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb-inner">
					<div class="content">
						<h3 class="title">My One Blog</h3>
						<ul class="page-list">
							<li class="list-item"><a href="{% url 'home:home' %}">Home</a></li>
							<li class="list-item"><a href="#"><h1 style="font-size: 16px;">All Categories</h1></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="blog-grid-wrapper three-column blog-grid-fashion" data-padding-top="100" data-padding-bottom="100">
	<div class="container">
		<div class="row">
			
            {% for ie in data %}
            <div class="col-md-6 col-lg-4">
				<div class="blog-grid-style-01">
					<div class="img-box"><img src="{{ie.image.url}}" alt="{{ie.h1}}"></div>
					<div class="content">
						<div class="post-meta">
							<ul class="post-meta-list">
								<li class="post-meta-item"><a href="#"><i class="las la-tag icon"></i> <span class="text">Total Posts: <b>{{ie.tot}}</b> </span></a></li>
							</ul>
						</div>
						<h4 class="title"><a href="{% url 'home:categoriesd' ie.slug %}">{{ie.category}}</a></h4></div>
				</div>
			</div>
            {% endfor %}
                
			
		</div>
        {% if data.has_other_pages %}
		<div class="row">
			<div class="col-lg-12">
				<div class="pagination" data-padding-top="50">
					
                    <ul class="pagination-list">
						{% if data.has_previous %}
                        <li><a href="?page={{ data.previous_page_number }}" class="page-number disable left-arrow"><i class="las la-angle-left"></i></a></li>
					    {% else %}

                    	<li><a href="javascript:void(0);" class="page-number disable left-arrow"><i class="las la-angle-left"></i></a></li>
                        {% endif %}
                        {% for i in data.paginator.page_range %}
                          {% if data.number == i %}
                          <li><span class="page-number current">{{i}}</span></li>
                          {% else %}  
                    
                        <li><a href="?page={{ i }}" class="page-number">{{i}}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if data.has_next %}
                        <li><a href="?page={{ data.next_page_number }}" class="page-number able right-arrow"><i class="las la-angle-right"></i></a></li>
					    {% else %}

                        <li><a href="javascript:void(0);" class="page-number able right-arrow"><i class="las la-angle-right"></i></a></li>
                        {% endif %}
                    </ul>


				</div>
			</div>
		</div>
        {% endif %}
	</div>
</div>
{% endblock body %}
    


{% block javascript %}
		
{% endblock javascript %}
    

home/templates/categories_blog.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}    
<title></title>
<meta name="description" content="" />
<link rel="canonical" href="https://www.myoneblog.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="" />
<meta property="og:description" content="" />
<meta property="og:url" content="https://www.myoneblog.com/" />
<meta property="og:site_name" content="My One Blog" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="" />
<meta name="twitter:title" content="" />

{% endblock seo %}

{% block css %}
{% endblock css %}
    


{% block body %}
<div class="breadcrumb-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb-inner">
					<div class="content">
						<h1 class="title">{{data3.category}}</h1>
						<ul class="page-list">
							<li class="list-item"><a href="{% url 'home:home' %}">Home</a></li>
							<li class="list-item"><a href="">Blogs</a></li>
							<li class="list-item"><a href="{% url 'home:categoriesd' data3.slug %}">{{data3.category}}</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="blog-area-wrapper Political-blog-grid-wrapper" data-padding-top="100" data-padding-bottom="100">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="two-column">
					<div class="row">
						
                        {% for ie in data %}
                        <div class="col-md-6 col-lg-6">
							<div class="blog-grid-style-03 small-02">
								<div class="img-box"><img src="{{ie.image.url}}" alt="{{ie.title}}"></div>
								<div class="content">
									<div class="post-meta">
										<ul class="post-meta-list style-02">
											<li class="post-meta-item"><a href="author-profile.html"><span class="text author">{{ie.author}}</span></a></li>
											<li class="post-meta-item date"><span class="text">{{ie.published}}</span></li>
										</ul>
									</div>
									<h4 class="title"><a href="{% url 'home:blogd' ie.slug %}">{{ie.title}}</a></h4></div>
                                    <p>{{ie.description}}... <a href="{% url 'home:blogd' ie.slug %}">read more</a></p>
							</div>
						</div>
						
                        {% endfor %}
                            

						 {% if data.has_other_pages %}
                            <div class="col-lg-12">
                                <div class="pagination" data-padding-top="50">
                                    
                                    <ul class="pagination-list">
                                        {% if data.has_previous %}
                                        <li><a href="?page={{ data.previous_page_number }}" class="page-number disable left-arrow"><i class="las la-angle-left"></i></a></li>
                                        {% else %}

                                        <li><a href="javascript:void(0);" class="page-number disable left-arrow"><i class="las la-angle-left"></i></a></li>
                                        {% endif %}
                                        {% for i in data.paginator.page_range %}
                                        {% if data.number == i %}
                                        <li><span class="page-number current">{{i}}</span></li>
                                        {% else %}  
                                    
                                        <li><a href="?page={{ i }}" class="page-number">{{i}}</a></li>
                                        {% endif %}
                                        {% endfor %}
                                        {% if data.has_next %}
                                        <li><a href="?page={{ data.next_page_number }}" class="page-number able right-arrow"><i class="las la-angle-right"></i></a></li>
                                        {% else %}

                                        <li><a href="javascript:void(0);" class="page-number able right-arrow"><i class="las la-angle-right"></i></a></li>
                                        {% endif %}
                                    </ul>


                                </div>
                            </div>
                        {% endif %}
					</div>
				</div>
			</div>
			<div class="col-sm-7 col-md-6 col-lg-4">
				<div class="widget-area-wrapper">
					{% include 'widget.html' %}
					<div class="widget">
						<div class="category style-01">
							<h4 class="widget-title style-01">Categories</h4>
							<ul class="widget-category-list">
                                
                                {% for ie in allcat %}
                                <li class="single-item"><a href="{% url 'home:categoriesd' ie.slug %}" class="wrap"><span class="left">{{ie.category}}</span>
                                     <span class="right">{{ie.tot}}</span></a></li>
							
                                {% endfor %}
                                    
                            </ul>
						</div>
					</div>
					<div class="widget">
						<div class="adds style-01">
							<a href="#"><img src="assets/img/ads-banner/half-page/03.jpg" alt=""></a>
						</div>
					</div>
					<div class="widget">
						<div class="recent-post style-01">
							<h4 class="widget-title style-01">Most Visted</h4>
							<ul class="news-headline-list style-01">
                                
                                {% for ie in data2 %}
                                <li class="news-heading-item">
									<h3 class="title"><a href="{% url 'home:blogd' ie.slug %}">
                                        {{ie.h1}}
                                    </a></h3>
									<div class="post-meta">
										<ul class="post-meta-list style-02">
											<li class="post-meta-item"><a href=""><span class="text author">{{ie.author}}</span></a></li>
											<li class="post-meta-item date"><span class="text">{{ie.published}}</span></li>
										</ul>
									</div>
								</li>
						        {% endfor %}
                                    
                                
							</ul>
						</div>
					</div>
					<div class="widget">
						<div class="tag style-01 black-bg">
							<h4 class="widget-title style-01">tags</h4>
							<ul class="tag-list">
								<li class="single-tag-item"><a href="#">News</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock body %}
    


{% block javascript %}
		
{% endblock javascript %}
    