advancedentalexport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from blog.views import blog_detail as bd
from blog.views import product_detail as pd
from home import views as myapp_views
from django.conf.urls import handler404, handler500

# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'MIT Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'My One Blog Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('sending-data/', include('enquiry.urls')),
    path('ultimate-smile-design/', include('usd.urls')),
    
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
    path('<str:pk>/', bd, name='blogd'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# handler404 = myapp_views.error_404
# handler500 = myapp_views.error_500

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('', views.blog_home, name='blog'),
    path('search-in-blogs', views.myblogsearch, name='myblogsearch'),
    path('all-blogs/', views.blog_list, name='blog_list'),
    path('all-blogs/<str:pk>/', views.cat_list, name='cat_list'),
] 

home/urls.py
from django.urls import path
from . import views
from blog.views import blog_detail as bd

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('verify-warranty/', views.verify_warrenty, name='verify_warrenty'),
    path('contact/', views.contact, name='contact'),
    path('contact-us/', views.contact_new, name='contact_new'),
    path('submit-stl-file/', views.stl, name='stl'),
    path('before-after/', views.beforeafter, name='beforeafter'),
    path('exhibition-gallery/', views.exhibition, name='exhibition'),
    path('career/', views.career, name='career'),
    path('event-gallery/<str:pk>/', views.eventgallery, name='eventgallery'),
    path('categories/', views.categories, name='categories'),
    path('categories/<str:pk>/', views.categoriesd, name='categoriesd'),
    path('blogs/', views.blogs, name='blogs'),
    path('search/', views.search, name='search'),
    path('gallery/', views.gallery, name='gallery'),
    path('terms-and-condition/', views.privacy, name='privacy'),
    path('cookie-policy/', views.cookie, name='cookie'),
    path('about-us/', views.about, name='about'),
    path('checkup/', views.checkup, name='checkup'),
    path('guest-posting/', views.gp, name='gp'),
    path('faq', views.faq, name='faq'),
    path('sitemap.xml/', views.sitemap, name='sitemap'),
    path('robots.txt/', views.robots, name='robot'),
    path('upload/', views.file_upload, name='upload'),
    path('testimonals/', views.testimonals, name='testimonals'),
    path('login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('web-story/', views.web_story, name='web_story'),
    path('web-story/<slug:story_slug>/', views.web_story_detail, name='web_story_detail'),
    # path('services/', views.service_view, name='service_view'),
    path('client-profile/<str:pk>/<str:fk>/', views.ext_api, name='ext_api'),
    path('print-order/', views.print_order, name='print_order'),
    path('print-payment/', views.print_payment, name='print_payment'),
    path('print-statments/<str:pk>/<str:did>/', views.print_statment, name='print_statment'),
    path('print-invoice/<str:pk>/<str:did>/', views.print_invoice, name='print_invoice'),
    path('api-login/', views.api_user_login, name='api_user_login'),
    path('api-logout/<str:pk>/<str:did>/', views.api_logout, name='api_logout'),
    # path('Events/', views.ade_events, name='Events'),
    # path('best-dental-lab/', views.bdl, name='bdl'),
    path('best-dental-lab-in-<str:pk>/', views.bdld, name='bdld'),
    path('blog/<str:pk>/', bd, name='blogd'),
    path('quicks-links/', views.connect, name='connect'),
]

usd/urls.py
from django.urls import path
from . import views
app_name='usd'
urlpatterns = [
    path('', views.usd, name='usd'),
    
] 

usd/models.py
from django.db import models

# Create your models here.

usd/views.py
from django.shortcuts import render, redirect

# Create your views here.
def usd(request):
    return redirect('https://ultimatesmiledesign.com/')

templates/api_login.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}    
<title>Login</title>
<meta name="description" content="The Grand Indian Route Login Page">
{% endblock seo %}

{% block css %}
<style>
    .header-btn2{
        background:#1d907c!important;
        color:white;
        border: 0px;
        padding:10px;
        width:100%;
        
    }
</style>
{% endblock css %}
    


{% block body %}
<hr>
    <div class="container py-5">
        <div class="content">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6 p-3">
                    <div class="login-content card mar-bottom-30 mar-top-30 ">
                        <div class="login-title section-border  text-center mt-3 ">
                            <h3>Client Login</h3></div>
                        <div class="login-form section-border">
                            <form action="" method="POST" class=" text-center pl-5 pr-5 pb-4">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control  mb-2 mt-2" name="username" placeholder="Enter username">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control  mb-2 mt-2" name="password" placeholder="Enter password">
                                </div>
                                <div class="form-btn">
                                    <input type="submit" class="header-btn2" value="LOGIN">
                                </div>
                            </form>
                            
                            <!-- <div class="form-group form-checkbox">
                               <a href="#">Forgot password?</a></div> -->
                        </div>
                    </div>
                </div>
             
            </div>
        </div>
    </div>
{% endblock body %}
    


{% block javascript %}
{% endblock javascript %}
    

templates/mobile.html
	{% load static %}
    <!-- MOBILE HEADER -->
    <div class="wsmobileheader clearfix">
        <a id="wsnavtoggle" class="wsanimated-arrow"><span></span></a>
        <span class="smllogo">
            <a href="{% url 'home:home' %}">
                <img src="{% static 'img/logo.png' %}" width="137" height="40" alt="mobile-logo"/>
            </a>
        </span>
        <a href="tel:+918469888877" class="callusbtn"><i class="fas fa-phone"></i></a>
     </div>

templates/pc.html
{% load static %}
<!-- NAVIGATION MENU -->
<div class="wsmainfull menu clearfix">
  <div class="wsmainwp clearfix container d-flex justify-content-between">
    <!-- LOGO IMAGE -->
    <!-- For Retina Ready displays take a image with double the amount of pixels that your image will be displayed (e.g 360 x 80 pixels) -->
    <div class="desktoplogo">
      <a href="{% url 'home:home' %}"><img src="{% static 'img/logo.png' %}" width="137" height="40" alt="header-logo" /></a>
    </div>

    <!-- MAIN MENU -->
    <nav class="wsmenu clearfix">
      <ul class="wsmenu-list">
        <!-- DROPDOWN MENU -->
        <li aria-haspopup="true">
          <a href="{% url 'home:home' %}"><span {% if request.path == '/' %}class="heasder_active"{% endif %}> Home</span></a>
        </li> <!-- END DROPDOWN MENU -->

        <li aria-haspopup="true">
          <a href="{% url 'home:about' %}"><span {% if request.path == '/about-us/' %}class="heasder_active"{% endif %}>About Us</span> </a>
        </li> <!-- END DROPDOWN MENU -->

        <li aria-haspopup="true">
          <span class="wsmenu-click"><i class="wsmenu-arrow"></i></span><a href="#"><span {% if request.path == '/' %}class=" "{% endif %} >Products</span> <span class="wsarrow"></span></a>
          <ul class="sub-menu">
            {% for ie in product %}
              <li aria-haspopup="true">
                <a href="{% url 'blogd' ie.slug %}">{{ ie.breadcrumb }}</a>

                {% if ie.sub %}
                  <ul class="sub-menu">
                    {% for i in ie.sub %}
                      <li aria-haspopup="true">
                        <a href="{% url 'blogd' ie.slug %}">{{ ie.breadcrumb }}</a>
                      </li>
                    {% endfor %}
                  </ul>
                {% endif %}
              </li>
            {% endfor %}
          </ul>
        </li>

        <li>
          <a href="https://ultimatesmiledesign.com">USD</a>
        </li>
        <!-- MEGAMENU -->

        <li>
          <a href="{% url 'blog:blog' %}"><span {% if request.path == '/blog/' %}class="heasder_active"{% endif %} >Blogs</span></a>
        </li>
        {% comment %} <li aria-haspopup="true">
          <a href="#">Resource Center <span class="wsarrow"></span></a>
          <div class="wsmegamenu clearfix">
            <div class="container">
              <div class="row">
                <!-- MEGAMENU QUICK LINKS -->
                <ul class="col-lg-3 col-md-12 col-xs-12 link-list">
                  <li class="title">Quick Links:</li>
                  <li>
                    <a href="{% url 'blog:blog' %}">Blogs</a>
                  </li>
                  <li>
                    <a href="{% url 'home:career' %}">Careers</a>
                  </li>

                  <li>
                    <a href="{% url 'home:gallery' %}">Gallery</a>
                  </li>
                  <li>
                    <a href="{% url 'home:exhibition' %}">Exhibition Gallery</a>
                  </li>
                  <li>
                    <a href="{% url 'home:beforeafter' %}">Before After</a>
                  </li>
                  <li>
                    <a href="{% url 'home:testimonals' %}">Testimonials</a>
                  </li>
                  <li>
                    <a href="{% url 'home:privacy' %}">Terms & Conditions</a>
                  </li>
                  <li>
                    <a href="https://play.google.com/store/apps/details?id=com.dental.doctore_app" target="_blank">Download App</a>
                  </li>
                  <li>
                    <a href="{% url 'home:verify_warrenty' %}">Verify Warranty</a>
                  </li>
                </ul>

                <!-- MEGAMENU FEATURED NEWS -->
                <div class="col-lg-5 col-md-12 col-xs-12">
                  <!-- Title -->
                  <h3 class="title">Featured Post:</h3>

                  <!-- Image -->
                  <div class="fluid-width-video-wrapper">
                    <img src="{{ main.image.url }}" alt="featured-news" />
                  </div>

                  <!-- Text -->
                  <h5 class="h5-xs"><a href="{% url 'blogd' main.slug %}">{{ main.h1 }}</a></h5>
                  <p class="wsmwnutxt">{{ main.description }}</p>
                </div> <!-- END MEGAMENU FEATURED NEWS -->

                <!-- MEGAMENU LATEST NEWS -->
                <div class="col-lg-4 col-md-12 col-xs-12">
                  <!-- Title -->
                  <h3 class="title">Latest Blogs:</h3>

                  <!-- Latest News -->
                  <ul class="latest-news">
                    {% for ie in latest %}
                      <!-- Post #1 -->
                      <li class="clearfix d-flex align-items-center">
                        <!-- Image -->
                        <img class="img-fluid" src="{{ ie.image.url }}" alt="blog-post-preview" />

                        <!-- Text -->
                        <div class="post-summary">
                          <a href="{% url 'blogd' ie.slug %}">{{ ie.description|truncatechars:'70' }}</a>
                        </div>
                      </li>
                    {% endfor %}
                  </ul>
                </div> <!-- END MEGAMENU LATEST NEWS -->
              </div> <!-- End row -->
            </div> <!-- End container -->
          </div> <!-- End wsmegamenu -->
        </li> {% endcomment %}
        <!-- END MEGAMENU -->

        <!-- SIMPLE NAVIGATION LINK -->

        <li class="nl-simple" aria-haspopup="true">
          <a href="{% url 'home:contact_new' %}"><span {% if request.path == '/contact-us/' %}class="heasder_active"{% endif %} >Contact</span></a>
        </li>
          <li class="nl-simple header-btn clss">
            <a href="https://client.advancedentalexport.com/">Client Login</a>
          </li>
          {% comment %} <li class="nl-simple header-btn d-none clss2">
            <a href="/api-logout/{{ pk }}/{{ did }}/">Logout</a>
          </li> {% endcomment %}

          <li class="nl-simple header-btn" aria-haspopup="true">
            <a href="{% url 'home:stl' %}">Submit STL File</a>
          </li>

          <!-- NAVIGATION MENU BUTTON -->
          <li class="nl-simple header-btn" aria-haspopup="true">
            <a href="{% url 'home:verify_warrenty' %}" target="_blank">Verify Warranty</a>
          </li>
    </nav> <!-- END MAIN MENU -->
  </div>
</div> <!-- END NAVIGATION MENU -->

templates/pdfview.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}    
<title></title>
<meta name="description" content="" />
<link rel="canonical" href="https://www.myoneblog.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="" />
<meta property="og:description" content="" />
<meta property="og:url" content="https://www.myoneblog.com/" />
<meta property="og:site_name" content="My One Blog" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="" />
<meta name="twitter:title" content="" />

{% endblock seo %}

{% block css %}
{% endblock css %}
    


{% block body %}
<section>
    <div class="container">
        <div class="row mt-5 pb-5">
            <div class="col-12">
                <a class="form-btn" href="{{link}}" target="_blank"> <u>Open In External Tab</u> </a>
                <iframe src="{{link}}"
                width="100%" height="900"> </iframe>
            </div>
        </div>
    </div>
</section>
{% endblock body %}
    


{% block javascript %}
		
{% endblock javascript %}
    

templates/template.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}    
<title></title>
<meta name="description" content="" />
<link rel="canonical" href="https://www.myoneblog.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="" />
<meta property="og:description" content="" />
<meta property="og:url" content="https://www.myoneblog.com/" />
<meta property="og:site_name" content="My One Blog" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="" />
<meta name="twitter:title" content="" />

{% endblock seo %}

{% block css %}
{% endblock css %}
    


{% block body %}

{% endblock body %}
    


{% block javascript %}
		
{% endblock javascript %}
    